# 1. Usamos la imagen oficial de Node.js (versión ligera)
FROM node:18-alpine

# 2. Creamos la carpeta de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiamos los archivos de dependencias e instalamos
COPY package*.json ./
RUN npm install --only=production

# 4. Copiamos el resto del código
COPY server.js .

# 5. Exponemos el puerto que usa Express
EXPOSE 3000

# 6. Comando para arrancar la app
CMD ["node", "server.js"]
