apiVersion: v1
kind: Service
metadata:
  name: backend-service # Este nombre va a ser el "DNS" interno
spec:
  type: ClusterIP # Servicio privado, solo accesible dentro del clúster
  selector:
    app: backend # Busca los pods que tengan la etiqueta "app: backend"
  ports:
  - port: 80         # Puerto en el que el Service escucha dentro del clúster
    targetPort: 3000 # Puerto del contenedor (el que definimos en el Deployment)